### ISSUE TITLE
KafkaSource and KafkaSink are not working anymore

### ISSUE THREAD

**Issue by Avoliq** [logbee/keyscore#1]
KafkaSource and KafkaSink are not working anymore. 

KafkaSource stops with: "Message [akka.kafka.KafkaConsumerActor$Internal$Stop$] without sender to Actor[akka://keyscore/system/kafka-consumer-2#2056765281] was not delivered. [3] dead letters encountered."

Kafka Sink stops with: "KafkaProducer - Closing the Kafka producer with timeoutMillis = 60000 ms."

I tried combining KafkaSource with StdOutSink and KafkaSink with HttpSource which produces the exact same errors, while a Stream with HttpSource and StdOut Sink works just as expected.

**Comment by kKdH** [comment]
Maybe it is time to write an integration test, because i'm not sure whether we fuck it up by upgrading some dependencies or due to the fact that we refactored many parts of the code base.

**Comment by kKdH** [comment]
I'm going to close this issue. By that time, it is clear that the kafka library we use does not support kafka older than 1.0

**Comment by kKdH** [comment]
I'm going to close this issue. By that time, it is clear that the kafka library we use does not support kafka older than 1.0
