### ISSUE TITLE
stopContainer fails - No value has been specified for property 'containerId'

### ISSUE THREAD

**Issue by mlandth** [logbee/keyscore#15]
When stopping a container with a bmuschko gradle task, e.g. the kafka stopContainer task, the task fails.
`No value has been specified for property 'containerId'.`
Therefore no container that was started from the bmuschko plugin in keyscore can be stopped and removed in keyscore.

**Comment by mlandth** [comment]
Blocks #14

**Comment by mlandth** [comment]
This issues seams to appear for every pulled image, whether pulled from dockerhub or quay.io.

**Comment by mlandth** [comment]
Solution: 
1. Creating a container:
`containerName = CONTAINER_NAME`

2. Using containerId:
`targetContainerId { task.getContainerName() }`

3. Use `DockerRemoveContainer`

**Comment by kKdH** [comment]
Thank you for clarification! :+1: Using a container name instead of an ID should not be a problem. Please let me know if you need further assistans!
