### ISSUE TITLE
Gradle  startContainers fails due to quay Exception.

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#23]
the task 'gradle startContainers' does fail locally with following Exceptions:

1. UnauthorizedException: "message":"Get https://docker.elastic.co/v2/elasticsearch/elasticsearch-oss/manifests/6.2.4: unauthorized: authentication required"

which is followed by:

2. InternalServerErrorException: {"message":"Get https://quay.io/v2/logbee/docker-kafka/manifests/latest: error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: \"Too many login attempts. \\nPlease reset your Quay password and try again.\""}

Seems only to be a promblem if you run the task locally. It works in Travis.

**Comment by EndallBatan93** [comment]
Maybe we need to set environment variables for running it locally ?

**Comment by kKdH** [comment]
I thought i build it that way that it works even with unset environment nor system variables. 🙈

Comment out line 41 to 50 of the build.gradle file in the root of the project.

‘‘‘groovy 
docker {
        if (dockerRegistryUserIsDefined && dockerRegistryPasswordIsDefined) {
            logger.info("Registry credentials set for: $dockerRegistryUrl")
            registryCredentials {
                url = dockerRegistryUrl
                username = "$dockerRegistryUser"
                password = "$dockerRegistryPassword"
            }
        }
    }
‘‘‘
