### ISSUE TITLE
Search function for Datasets

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#41]
- [x] add the functionality to search through datasets, weather search for keys, values or everything

- [x] the Ui-element for the search should be placed in the datasets-visualizer component

**Comment by kKdH** [comment]
Maybe we should take a look at the query language used in Kibana. For example to searching for a field with a given value the syntax is: `field:value`

**Comment by reimarstier** [comment]
https://lucene.apache.org/core/3_6_0/queryparsersyntax.html
