### ISSUE TITLE
KafkaSink Descriptor can not be translated

### ISSUE THREAD

**Issue by Avoliq** [logbee/keyscore#44]
The Agent is not able to translate the KafkaSink Descriptor. On Registering the KafkaSink extension the Agent throws an 

`java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key category2`

In `Localization.scala ` on Line 37 it tries to get the `TextRef(category2)` String from the bundle which is not there.
But i have to admit that i have no idea why it even tries to resolve the `category2` key.

**Comment by EndallBatan93** [comment]
Fix by ed02e777f3a7f6308235665c7d3d09912b47d239
