### ISSUE TITLE
Pipeline with  two identic filters only instantiates one.

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#51]
**Problem**: Create a pipeline with the pipely-editor with a Kafka source and a Kafka sink and put two identic filters between like two LoggerFilters or two AddFieldsFilters . When you run the pipeline in the editor there are only three resources created. Sink Source and one instance of the filter. 
The second one is missing. 

**Question**: This may be a FrontEnd or a BackEnd problem, somewhere in between the second configuration goes missing.

**Comment by kKdH** [comment]
@EndallBatan93 can you enhance the integration test to reproduce the problem?

**Comment by EndallBatan93** [comment]
Problem definitely is related to pipely.

**Comment by Avoliq** [comment]
fixed with b6c19a5
