### ISSUE TITLE
Generic "Go to Pipeline" button on Live Editing page

### ISSUE THREAD

**Issue by kKdH** [logbee/keyscore#59]
We should use a generic "go to pipeline" button with a proper icon instead of a back button, because when the user enters live editing from resources page (i known it is a dev feature) than the button does not route back to the resources page.

![Generic "Go to Pipeline" button](https://screenshotscdn.firefoxusercontent.com/images/466ccdeb-7aab-443f-8810-ec6a29ea3b14.png)

**Comment by EndallBatan93** [comment]
Good point though going to Chance that tomorrrow.
