### ISSUE TITLE
Configuration Store

### ISSUE THREAD

**Issue by kKdH** [logbee/keyscore#6]
The actual workflow provides that a user creates a PipelineConfiguration within the KS:M.
The configuration is send to the KS:F and from there to an agent which materializes the
configuration into a several stages and starts these stages. So there is currently no way
to just store a PipelineConfiguration without starting a pipeline.

**Comment by mlandth** [comment]
Problem 1: 764c040b1f1b42163dcdc898fded2d68da4c442e @kKdH implemented a ConfigurationRepository.
Also the new API handles storing configurations and running a pipeline separately.

**Comment by kKdH** [comment]
First steps are made to solve the problems regarding this issue. Going to close this one in favour of #53 and #54.
