### ISSUE TITLE
Broken layout of configurator when using smaller browser window

### ISSUE THREAD

**Issue by kKdH** [logbee/keyscore#61]
![Broken layout of configurator when using small browser window](https://screenshotscdn.firefoxusercontent.com/images/b773d8ee-3dc9-4529-9638-8590da551ce1.png)

**Comment by EndallBatan93** [comment]
This also happens when the messages in a dataset are too long. 
The table adjusts to content size and therefore destroys the layout.

**Comment by kKdH** [comment]
Additionally look at the control to scroll through the datasets. It shouldn't insert line-breaks into the display of the current and the remaining datasets.

**Comment by EndallBatan93** [comment]
Not really sure that I understand what you mean.
Gonna look into it.

**Comment by kKdH** [comment]
Ugly:
```
<  6  >
   /
  10
```

Pretty:
```
<  6 / 10  >
```

**Comment by EndallBatan93** [comment]
Damn thought I fixed that already :(

**Comment by kKdH** [comment]
Ah...i'm not up-to-date. So maybe i have to pull...sorry
