### ISSUE TITLE
General Live-Editing improvements to improve usability

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#64]
- [x] 1. Search function does currently not work case insensitive. (Example: Currently when you search fo 'INFO' by typing info you get no result.) 
- [ ] 2. Collapse button style is broken when clicked, needs to be adjusted.
- [x] 3. Icon for search function. To highlight the search function i want to add a magnifiying glass.
- [x] 4. Button naming needs to be reworked.
- [x] 5. Empty table cells should contain information about the added or deleted fields. In the evaluation some peple were irritated thate the cells are empty and suggested, that we there could place information eg: 'Field was deleted', 'Field was added' .
- [x] ~~6. new icon for live-editing in the pipely editor.
 Currently we are using a gear icon at each block which was often missinterpreted as settings. To prevent this we should make a new icon that is more fitting.(not needed when the integration into pipely happens)~~

**Comment by kKdH** [comment]
Hey @EndallBatan93 can you give us more information about some of your points?

> Search function does currently not work case sensitive.

Do you really want a case sensitive search? Or do you want to add the possibility to enforce case sensitive search? Eg. surrounding the search term in quotes. 

>  Empty table cells should contain information about the added or deleted fields.

What kind of information?

> New icon for live-editing

What kind of icons? Which icons do you want to replace?

> snackbars should be displayed longer or until the user dismisses them.

This is the case for all snackbars, not only in live editing.
