### ISSUE TITLE
Reworking Live-Editing for Sink an Source.

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#65]
Current behaviour: 
When the live editing feature is used on a sink, currently there is no data change highlighted.
Thats because the input and outputdata is the same. 

Expected behaviour:
Live-Editing on sink should show the input datasets from the source with the output data of the sink, so you can actually see the whole pipeline transformation. 

Another thing is, that we should disable the footer row in configurator component when configuring a source or a sink.

**Comment by kKdH** [comment]
IMHO: Disable LE for Sinks and Sources.

**Comment by EndallBatan93** [comment]
Well ok,  that's one way to deal with it. I just thought it would be more intuitive, because  if the user wants to see the output of his pipeline he automatically would look at the sink. 
If we disable the live-editing for sink and sources the user hast to use the live-editing of it's last and first filter.

**Comment by Avoliq** [comment]
> I just thought it would be more intuitive, because if the user wants to see the output of his pipeline he automatically would look at the sink.

Considering the experience during the user study I would also say the Sink LE is essential. 
Every participant used the Sink LE to check the result of the pipeline

**Comment by kKdH** [comment]
Ok. Ok. Overvoted 😜

Lets do it.

**Comment by EndallBatan93** [comment]
This issue is part of the live-editing integration in pipely #66
