### ISSUE TITLE
Travis build breaking due to sass-loader exception.

### ISSUE THREAD

**Issue by EndallBatan93** [logbee/keyscore#82]
Since the modules refactoring travis breaks with the following message:

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)

The log als suggests, to look up the supported environments here: 
https://github.com/sass/node-sass/releases/tag/v4.8.3

But Linux 64-bit should be supported. 

When researching the error, i found a lot of possible solutions like: npm rebuild node-sass

But this seems unhelpful because Travis does start over fresh in each build, or not ?

**Comment by kKdH** [comment]
It seams to be a problem with the travis cache.
